pizza-pizza-app/config/routes.rb
Rails.application.routes.draw do

  root to: 'application#home'

  resources :toppings
  resources :pizzas
  resources :users
  resources :pizza_toppings

  resources :login, only: [:new, :create]

  get "/login", to: 'login#new', as: "login"
  post "/login", to: 'login#create'
  delete "/logout", to: 'login#destroy'
end

pizza-pizza-app/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

pizza-pizza-app/app/models/pizza.rb
class Pizza < ApplicationRecord
  belongs_to :user
  has_many :pizza_toppings, dependent: :delete_all
  has_many :toppings, through: :pizza_toppings
end

pizza-pizza-app/app/models/pizza_topping.rb
class PizzaTopping < ApplicationRecord
  belongs_to :pizza
  belongs_to :topping
end

pizza-pizza-app/app/models/topping.rb
class Topping < ApplicationRecord
  has_many :pizza_toppings
  has_many :pizzas, through: :pizza_toppings
end

pizza-pizza-app/app/models/user.rb
class User < ApplicationRecord
  has_secure_password

  has_many :pizzas, dependent: :destroy

  validates_uniqueness_of :username
  validates :password, length: { minimum: 8 }

end

pizza-pizza-app/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :setup_auth_variables

  def setup_auth_variables
    @user_id = session[:user_id]
    @logged_in = !!@user_id
    if @logged_in
      @current_user = User.find(@user_id)
    end
  end

  def authorized
    if !@logged_in
      return redirect_to '/'
    end
  end

  def logout
    session.clear
    # session[:user_id] = nil
  end

  def home

  end

end

pizza-pizza-app/app/controllers/login_controller.rb
class LoginController < ApplicationController
  skip_before_action :setup_auth_variables

  def new

  end

  def create
    @user = User.find_by(username: params[:username])
    if @user && @user.authenticate(params[:password])
      flash["message"] = "Successfully logged in #{@user.first_name}!"
      session[:user_id] = @user.id
      redirect_to @user
    else
      flash["message"] = "Incorrect Username or Password"
      redirect_to new_login_path
    end
  end

  def destroy
    logout
    redirect_to "/"
  end

end

pizza-pizza-app/app/controllers/pizza_toppings_controller.rb
class PizzaToppingsController < ApplicationController

	def create
		@pizza = Pizza.create(user_id: session[:user_id], order_number: 1)
		# loop through toppings creat pizzatoppoing
		num_toppings = pizza_topping_params[:topping_id].length
		pizza_topping_params[:topping_id][1...num_toppings].each do |t_id|
			PizzaTopping.create(pizza: @pizza, topping_id: t_id)
		end
		redirect_to pizza_path(@pizza)
	end

	def update
		@pizza = Pizza.find(pizza_topping_params[:pizza_id])
		num_toppings = pizza_topping_params[:topping_id].length

		# get the toppings user has selected and the toppings already on the pizza
		selected_toppings = pizza_topping_params[:topping_id]
		current_toppings = @pizza.toppings.pluck(:id)
		
		# check if a topping on current pizza has been deselected
		current_toppings.each do |ct|
			if !selected_toppings.include?(ct.to_s)
				PizzaTopping.where(topping_id: ct, pizza: @pizza)[0].destroy
			end
		end
		selected_toppings.each do |st|
			if !current_toppings.include?(st.to_i)
				PizzaTopping.create(pizza: @pizza, topping_id: st.to_i)
			end
		end
		redirect_to pizza_path(@pizza)
	end

	private

	def pizza_topping_params
		params.require(:pizza_topping).permit(:pizza_id, :topping_id => [])
	end
end

pizza-pizza-app/app/controllers/pizzas_controller.rb
class PizzasController < ApplicationController
	def new

		# get a template for a pizzatopping
		# get all the toppings
		@pizzatopping = PizzaTopping.new
		@toppings = Topping.all
		# show all the toppings in the view and the form for a pizzatopping
	end

	def show

		@pizza = Pizza.find(params[:id])
		@pizzas_toppings = @pizza.toppings
	end

	def edit
		@pizza = Pizza.find(params[:id])
		@pizzas_toppings = @pizza.toppings.pluck(:id)
		@toppings = Topping.all
	end

	def destroy
		@user = User.find(session[:user_id])
		@pizza = Pizza.find(params[:id])
		@pizza.destroy
		redirect_to user_path(@user)
	end

	private

	def pizza_params
		require(:pizza).permit(:topping_id => [])
	end
end

pizza-pizza-app/app/controllers/toppings_controller.rb
class ToppingsController < ApplicationController
end

pizza-pizza-app/app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authorized, only: [:show, :edit, :destroy]
  skip_before_action :setup_auth_variables, only: [:new, :create]

  def new
    @user = User.new
  end

  def create
    @user = User.create(user_params)
    if @user.valid?
      session[:user_id] = @user.id
      redirect_to @user
    else
      flash[:errors] = @user.errors.full_messages
      redirect_to new_user_path
    end
  end

  def edit
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])
    if @user.update(user_params)
      redirect_to @user
    else
      flash[:errors] = @user.errors.full_messages
      redirect_to edit_user_path
    end
  end

  def destroy
    @user = User.find(session[:user_id])
    @user.destroy
    logout
    redirect_to '/'
  end

  def show
    @user = User.find(params[:id])
    @pizzas = @user.pizzas
  end

  private

  def user_params
    params.require(:user).permit(:first_name, :username, :address, :password)
  end

end

pizza-pizza-app/app/helpers/application_helper.rb
module ApplicationHelper
end

pizza-pizza-app/app/helpers/login_helper.rb
module LoginHelper
end

pizza-pizza-app/app/helpers/pizza_topping_helper.rb
module PizzaToppingHelper
end

pizza-pizza-app/app/helpers/pizzas_helper.rb
module PizzasHelper
end

pizza-pizza-app/app/helpers/toppings_helper.rb
module ToppingsHelper
end

pizza-pizza-app/app/helpers/users_helper.rb
module UsersHelper
end

pizza-pizza-app/app/views/application/home.html.erb
<center>
<h1>Welcome To</h1>
<h1 id="p_p">🍕Pizza Pizza!🍕</h1>
</center>

pizza-pizza-app/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>PizzaPizzaApp</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>

    <link href="https://fonts.googleapis.com/css?family=Faster+One|Grand+Hotel|Pridi&display=swap" rel="stylesheet">
  </head>

<header>
  <nav>
    <span class="go_home"> <%= link_to image_tag("pizza_pie.png", height: '40', width: '40'), root_path %> </span>

      <% if @logged_in %>

      <span> Logged in: <%= @current_user.username %> </span>
      <span> <%= link_to "View Profile", @current_user  %> </span>
      <span> <%= link_to "Edit Profile", edit_user_path(@current_user) %> </span>
      <span> <%= button_to "Delete Profile", @user, method: :delete %> </span>
      <span> <%= link_to "Cook Pizza", new_pizza_path %> </span>
      <span> <%= button_to "Logout", "/logout", method: :delete %> </span>

    <% else %>

      <span> <%= link_to "Login", new_login_path %> </span>
      <span> <%= link_to "Register", new_user_path %> </span>

    <% end %>
  </nav>
</header>

  <body>
    <%= yield %>
  </body>
  <script type="text/javascript">

    var dist = function (x1, y1, x2, y2) {
      let deltaX = Math.abs(x2 - x1)
      let deltaY = Math.abs(y2 - y1)
      let distancesquared = Math.pow(deltaX, 2) + Math.pow(deltaY, 2)
      return Math.floor(Math.sqrt(distancesquared))
    }

    var toppings = document.querySelectorAll(".topping_name")
    var pie = document.querySelector(".pie")
    toppings.forEach((topping) => {
      topping.addEventListener("click", function () {
        let id = topping.getAttribute("for");
        let topping_name = topping.innerText;
        let topping_box = document.querySelector(`#${id}`);
        if (!topping_box.checked) {
          prev_left = 0;
          prev_top = 0;
          for (let i = 1; i <= 20; i ++) { 
            var seed = Math.floor(Math.random() * 100)/100
            var left = seed * 18
            var top = seed * 18
            if (dist(left, top, prev_left, prev_top) < 10) {
              if (Math.floor(Math.random() * 2))
                left = left < 14 ? left + 5 : left - 5
              else
                top = top < 10 ? top + 10 : top - 10
            }
            var rotate = Math.floor(seed * 360)
            pie.innerHTML +=`<div class=\"${topping_name.toLowerCase()}\" style=\"top:${top}em;left:${left}em;transform: rotate(${rotate}deg);\"></div>`;
          }
        }
        else {
          let tops_to_rem = document.querySelectorAll(`[class^=${topping_name.toLowerCase()}`);
          tops_to_rem.forEach((top) => {
            top.remove()
          });
        }

      })
    })
  </script>
</html>

pizza-pizza-app/app/views/login/new.html.erb
<h1>Login</h1>

<div id="login">
<%= form_tag "/login" do %>
  <%= label_tag :username %>
  <br>
  <%= text_field_tag :username %>
  <br>
  <%= label_tag :password %>
  <br>
  <%= password_field_tag :password %>
  <br>
  <%= submit_tag "Login" %>
<% end %>
</div>

pizza-pizza-app/app/views/pizzas/edit.html.erb
<h1>Edit Pizza</h1>

<div id="pizza_form">
<h2>Toppings:</h2>
<%= form_tag("/pizza_toppings/update", method: :put) do %>
	<%= hidden_field(:pizza_topping, :pizza_id, :value => @pizza.id) %>
  <% @toppings.each do |t| %>
	  	<%= check_box_tag name = "pizza_topping[topping_id][]", value = t.id , checked = @pizzas_toppings.include?(t.id), class: "topping_check", id: "pizza_topping_topping_id_#{t.id}"%>
	  	<label for="pizza_topping_topping_id_<%= t.id %>" class="topping_name"><%= t.name %></label>
  <% end %>
  <%= submit_tag("Cook It! I'm Hungry dude.") %>
<% end %>
</div>

pizza-pizza-app/app/views/pizzas/new.html.erb
<div id="pizza_form">
	<%= form_for @pizzatopping do |f| %>
		<h2> <%= f.label :topping_id %> </h2>
		<br>
		<%= f.collection_check_boxes(:topping_id, @toppings, :id, :name) do |b| %>
			<%= b.check_box(class: "topping_check") %>
			<%= b.label(class: "topping_name") %>
		<% end %>
		<br>
		<br>
		<%= f.submit "Create Pizza! "%>
	<% end %>
	<br>
	<div>
		<div class="pie">
		</div>
	</div>
</div>

pizza-pizza-app/app/views/pizzas/show.html.erb
<h1>Pizza <%= @pizza.id %></h1>
<div id="pizza_form">
	<ul>
		<% @pizzas_toppings.each do |topping| %>
			<li><%= topping.name %></li>
		<% end %>
		<% if @pizzas_toppings.length > 0 %>
			<%= link_to "Edit this pizza", edit_pizza_path(@pizza) %>
		<% end %>
		<%= button_to "Delete this pizza", pizza_path(@pizza), method: :delete %>
</ul>
</div>

pizza-pizza-app/app/views/users/_form.html.erb
<div id="user_form">
  <%= form_for @user do |f| %>
    <div class="user_input">
    <%= f.label :first_name %>
    <br>
    <%= f.text_field :first_name %>
    </div>
    <div class="user_input">
    <%= f.label :username %>
    <br>
    <%= f.text_field :username %>
    </div>
    <div class="user_input">
    <%= f.label :address %>
    <br>
    <%= f.text_field :address %>
    </div>
    <div class="user_input">
    <%= f.label :password %>
    <br>
    <%= f.password_field :password %>
    </div>
    <div class="user_input">
    <%= f.submit %>
    </div>

  <% end %>
</div>

pizza-pizza-app/app/views/users/edit.html.erb
<h1>Edit Profile</h1>


<%= render 'form' %>

pizza-pizza-app/app/views/users/new.html.erb
<div id="register">

  <h1>Registration</h1>

  <div id="errors">
  <% if flash[:errors] %>
  <span>  <i>Please note,</i> your account could not be created because:  </span>
    <ul>
      <% flash[:errors].each do |err_message| %>
      <li>
          <%= err_message %>
      </li>
      <% end %>
    </ul>
  <% end %>
  </div>

</div>

<%= render 'form' %>

pizza-pizza-app/app/views/users/show.html.erb
<div id="user_show">

  <div id="user_info">
    <h1><%= @user.first_name %>'s Pizzas!</h1>
    <p>Address: <%= @user.address %></p>
  </div>

  <div id="user_pizzas">

  <h1>All the Pies!</h1>
  <ul>
    <% @pizzas.each do |p| %>
    <li>
      <%= link_to "Pizza ##{p.id}", pizza_path(p) %> with...
        <% p.toppings.each do |topping| %>
          <br>
          <%= topping.name %>
        <% end %>
    </li>
    <% end %>
  </ul>
  </div>

</div>